### PR TITLE
Fix bug when using object storage (#566)

### PR DESCRIPTION
**Pull request by iolate**
blank files return false when using object storage as primary storage

* resolved: nextcloud#566

### CODE REVIEW

**Review by korelstar — CHANGES_REQUESTED** [review]
Thank you very much for your contribution! 🚀 

I'm afraid that your change breaks error handling. In the past, we had the problem that for some people a specific encrypted file can't be read (internal Nextcloud problem). In this case, `File:getContent()` also returns `false`. However, we must not return an empty content in this situation, but we have to throw an error (like before). Otherwise, it may happen that the user accidentally overwrites his note with empty content.

Therefore, we have to find another solution for this. I would be happy if you could help with finding a sustainable solution! 👍

**Comment by iolate** [comment]
Then how about like this? I added a condition to check that file size is 0

**Comment by korelstar** [comment]
Easy and effective - I think this is a good solution, thanks!

The linter complains that `Inline control structures are not allowed`. Could you please fix this? I will merge this PR then.

**Comment by iolate** [comment]
Thank you!
Should I rebase my commits? I'm not familiar with pull request.. :(

**Comment by korelstar** [comment]
Thank you very much! 🎉 

Everything is fine, now. :-)

**Pull request merged**
