### PR TITLE
Categories in navigation

### PR DESCRIPTION
**Pull request by korelstar**
Next step to provide categories to the frontend (see #8).

This PR is only about the navigation on the left side. The goal is to provide a list of existent categories with the possibility to filter the list of notes by the currently selected category. The design should orient on similar selectors of other Nextcloud apps as well as on the Android app. Changing the current note's category must be done in a separate PR (see #228).

## Tasks done
- [x] show list of categories in the navigation bar (left side)
  - generate list from current notes
  - show only first level of categories
- [x] make these entries selectable
- [x] filter list of notes by current selection
- [x] show the number of notes per category as counter
- [x] when using the "New note" button, the new note is assigned automatically to the currently selected category
- [x] don't show favorites as navigation item (see discussion in the comments)
- [x] don't auto-close navigation after clicking on category (only on small screens)
- [x] group notes by category, if there is a sub-category (like in the Android app)

## Feedback
Please feel free to test and give feedback, especially from the design perspective. @nextcloud/designers @jancborchardt 
I will also provide some screenshots ...

### CODE REVIEW

**Comment by korelstar** [comment]
# Screenshots of the current implementation

## Default view:
grafik


## ... after clicking on "Categories" (collapsible):
grafik


## ... after clicking on the category "Test":
grafik

**Comment by korelstar** [comment]
Oh, and please note: currently, only the first level of categories is shown in the navigation. E.g., if there are notes in the folders `Test/A/`, `Test/B/` and `Moin`, then the list of categories in the navigation is `Test`, `Moin`.

**Comment by jancborchardt** [comment]
Hmm, the 2-level navigation is a bit confusing, and not fully necessary:
- recent is the default sorting
-favorites should be sorted up top anyway
- so the categories are the only thing left to display

I would prefer to see mockups or sketches, no matter how quick and dirty, before we rush into implementation. :) That way we can see how stuff works, and don't waste work on things which don't.

**Comment by korelstar** [comment]
If you prefer to talk about mockups, then imagine that my implementation is a mockup ;-)

In order to make the list slim, we could remove the favorites item, of course. And note, that the search will be (re)moved, too (see #43). But we cannot remove the recent item, since otherwise, you cannot go back from a specific category to the whole list of notes. We can rename this item though.

However, the list of categories can be quite long (I'm using 11 first-level categories + uncategorized, in my personal notes). This would take much space from the screen (especially on mobile screens) and would require scrolling down in order to see the first notes items.

We would have to go with a second navigation then, like in the contacts app. In my personal opinion, this would be too distracting when writing notes. But if you prefer this, we could go this way.

I still think that my approach (showing categories on demand, using official Nextcloud design approaches) is best in giving access to categories and being not distracting when not using categories.

What's your proposal?

**Comment by stefan-niedermann** [comment]
absolutely, looks great!

**Comment by BloodyIron** [comment]
How do you set categories in the new method? Drag and drop, or right click on the note, or what?

**Comment by BloodyIron** [comment]
Also, since this is the last item for the 2.5.0 milestone, any chance we could get this wrapped up and usable please? :DDD

**Comment by korelstar** [comment]
See the screenshots in #228 for the current implementation of editing.

We have to do some testing and fixing the last bugs before releasing.

You can help in testing the latest state from master. Or you can increase the bounty on #8 in order to speed this up ;-)

**Pull request merged**
