### PR TITLE
Also show notes inside subdirectories

### PR DESCRIPTION
**Pull request by Henni**
First step towards owncloud/notes#2

TODO:
- [x] Fix (Maybe rewrite) tests

### CODE REVIEW

**Comment by Henni** [comment]
Seems like a transifex update from owncloud snuck in. I'll "force-fix" this.

**Comment by korelstar** [comment]
Nice! I'm really looking forward to this feature.

Do you plan a "silent" integration of subdirs (the source of the note is omitted, they are all shown in one list of notes) or should the subdirs be shown in the GUI as "folders" (like a contact group in the contacts app)? The second variant would directly influence #2, because the navigation sidebar could then show the list of folders instead the list of notes and a second sidebar could be needed (like in the contacts app). I like that concept because it would be possible to structure the notes in a better way.

/cc @jancborchardt

**Comment by Henni** [comment]
For not it is "silent".
The goal is to create some kind of structure (categorization) with the help of the subdirectories.
But I'd prefer to keep it simple and maybe integrate it into the already existing sidebar. (let's talk about this in #8)

**Comment by jancborchardt** [comment]
CC'ing the people who were involved in the discussion on subfolders for Notes in the original issue. :) You’ll probably like that work is being done on it here! :tada:

Reviews are very welcome!
@caco3 @pyluyten @lpalgarvio @reimersjan @slashrsm @Jas2Ma @grefel @pierrejochem @greenais @rakshazi @sprnza @pbek @olantrust @xraMsamohT @dasmaetthes @jibweb

**Comment by dasmaetthes** [comment]
Very nice,
Would it work also with owncloud or nextcloud only?

**Comment by jancborchardt** [comment]
@dasmaetthes it will likely work with ownCloud as well for the near future. However as most people developing on these apps (also like Calendar, Contacts and Mail) moved to Nextcloud and don’t necessarily test with both systems, bugs could occur in the future. So we recommend to upgrade. :)

**Comment by Henni** [comment]
@dasmaetthes *should* work with owncloud as well. Tests on owncloud are welcome :)

**Comment by dasmaetthes** [comment]
Seems to work well with owncloud.

Thank you very much.

**Comment by evaryont** [comment]
Just wondering if there is anything blocking this from being merged?

**Comment by Henni** [comment]
@evaryont the tests should be fixed before merging this.

**Comment by korelstar** [comment]
@Henni 
I've fixed the tests, rebased the branch and added a new attribute `category` for the `Note` entity which is filled with the subdir name. I suggest to merge this now since some people are waiting for this impatiently ... :grin:

**Comment by Henni** [comment]
I removed two debug lines which I left in.

After travis has finished I'll merge this and release notes 2.2

**Comment by jancborchardt** [comment]
Awesome work! :) :tada:

**Pull request merged**
