### PR TITLE
fix Application setup / move nav to info.xml

### LINKED ISSUE #524: RuntimeException: App class OCA\Notes\Application is not setup via query() but directly
This error is getting spammed in the logs at a very high frequency.

I tried the same fix as for Maps, ref https://github.com/nextcloud/maps/issues/384 but it didn’t work. @korelstar I’m sure you know what to do. :) There’s also further pointers in the issue as Calendar had a similar problem.

```
[notes] Error: RuntimeException: App class OCA\Notes\Application is not setup via query() but directly at <<closure>>

0. /home/jan/nextcloud/apps/notes/lib/Application.php line 12
   OCP\AppFramework\App->__construct("notes", [])
1. /home/jan/nextcloud/apps/notes/appinfo/app.php line 3
   OCA\Notes\Application->__construct()
2. /home/jan/nextcloud/lib/private/legacy/OC_App.php line 272
   require_once("/home/jan/nextc ... p")
3. /home/jan/nextcloud/lib/private/legacy/OC_App.php line 155
   OC_App::requireAppFile("notes")
4. /home/jan/nextcloud/lib/private/legacy/OC_App.php line 128
   OC_App::loadApp("notes")
5. /home/jan/nextcloud/lib/base.php line 993
   OC_App::loadApps()
6. /home/jan/nextcloud/index.php line 37
   OC::handleRequest()

GET /nextcloud/index.php/apps/logreader/poll?lastReqId=vsC4lkLBioYFgOnlmoZx
from 127.0.0.1 by jan at 2020-05-30T13:33:58+00:00
```

### PR DESCRIPTION
**Pull request by korelstar**
fix #524

### CODE REVIEW

**Comment by jancborchardt** [comment]
Seems to still work, but I’m actually getting different errors creating notes – possibly unrelated?

"Creating new note has failed. See JavaScript console and server log for details"

Server log:
```
[notes] Error: OCP\Files\NotPermittedException: Could not create path at <<closure>>

 0. /home/jan/nextcloud/apps/notes/lib/Service/NotesService.php line 63
    OC\Files\Node\Folder->newFile("New note.txt")
 1. /home/jan/nextcloud/apps/notes/lib/Controller/NotesController.php line 122
    OCA\Notes\Service\NotesService->create("jan", "", "")
 2. /home/jan/nextcloud/apps/notes/lib/Controller/Helper.php line 28
    OCA\Notes\Controller\NotesController->OCA\Notes\Controller\{closure}("*** sensitive parameters replaced ***")
 3. /home/jan/nextcloud/apps/notes/lib/Controller/NotesController.php line 125
    OCA\Notes\Controller\Helper->handleErrorResponse(Closure {})
 4. /home/jan/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 169
    OCA\Notes\Controller\NotesController->create("")
 5. /home/jan/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Notes\Controller\NotesController {}, "create")
 6. /home/jan/nextcloud/lib/private/AppFramework/App.php line 137
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Notes\Controller\NotesController {}, "create")
 7. /home/jan/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Notes\\Controller\\NotesController", "create", OC\AppFramework\ ... {}, {_route: "notes.notes.create"})
 8. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "notes.notes.create"})
 9. /home/jan/nextcloud/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "notes.notes.create"})
10. /home/jan/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/apps/notes/notes")
11. /home/jan/nextcloud/index.php line 37
    OC::handleRequest()

POST /nextcloud/index.php/apps/notes/notes
from 127.0.0.1 by jan at 2020-06-01T00:27:50+00:00
```

**Comment by korelstar** [comment]
Hmm. Indeed, that issue sounds unrelated. However, I would like to analysis it in more detail.

Does this also happen when using `master` branch? Are you able to create a file in your notes directory using the files app?

**Comment by jancborchardt** [comment]
Merging this for now – I’ll investigate more regarding the issue as I can reproduce on master. :)

**Comment by jancborchardt** [comment]
I did a full uninstall, removed the "Notes" folder, installed it again, now it works. Thanks for the hint on the Notes folder via Files. :)

**Pull request merged**
