### PR TITLE
new undo design using notifications

### LINKED ISSUE #417: Design of Undo deletion
Follow up of #398.
The design has to be fixed, see: https://github.com/nextcloud/nextcloud-vue/issues/705

### PR DESCRIPTION
**Pull request by korelstar**
Fixes  #417, see discussion under https://github.com/nextcloud/nextcloud-vue/issues/705, especially https://github.com/nextcloud/nextcloud-vue/issues/705#issuecomment-549194181. Thanks to @paulschwoerer for help on implementing this. For now, I'm using the (old) `OC.Notification` API, since I want to be compatible to Nextcloud 15/16. We will switch to the new `OCP.Toast` API later.

grafik

@jancborchardt Is this how you imagined?

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice!

Let’s call it "Undo deletion", and does it maybe look more clickable if we make it a button?

Also, the `[ ]` were just a visualization for the button when I wrote the mockup in text – they should not be there. :)

**Comment by korelstar** [comment]
I did a complete re-work of this (backend deletes directly and re-creates on undo, fronted uses @nextcloud/dialogs). Here are some impressions:

### deleting a single note

Screenshot

The Toast is closed after a timeout of 12 seconds. I used a longer timeout than normal due to the discussion under https://github.com/nextcloud/nextcloud-vue/issues/705#issuecomment-574156629

### deleting multiple notes

If another note is deleted before the timeout is expired, the Toast is adjusted and the timeout is reset:

Screenshot

Pressing "Undo delete" will restore all deleted notes within the timeout-period (here: three).

**Comment by jancborchardt** [comment]
So @skjnldsv and I recently talked about Undo, so looping him in. :)

Also @korelstar only one thing about the notification: To prevent misclicks and accidental closing of the notification when you actually want to undo, can we remove the X button? It will automatically close anyway. :)

**Comment by skjnldsv** [comment]
Oooh, never seen this!! :O
See https://github.com/nextcloud/nextcloud-dialogs/pull/106

**Comment by korelstar** [comment]
Of course, we can remove the "x" button.

I'm already watching https://github.com/nextcloud/nextcloud-dialogs/pull/106, where a standardization is developed (there, the "x" button is removed). As far as I can see, that approach is similar, so I would switch so the standardized solution, when finished.

**Comment by skjnldsv** [comment]
You rock!

**Pull request merged**
