### PR TITLE
Checkbox functionality

### PR DESCRIPTION
**Pull request by tnyeanderson**
#117 Adds basic checkbox functionality.

Known bugs:
* Double/Triple checkboxes on some double/triple clicks
* Clicking the very bottom of a checkbox will check the box below it

### CODE REVIEW

**Comment by tnyeanderson** [comment]
Not sure where to start diagnosing the Travis CI build fail... Did I not sign it correctly or something?

**Comment by Grotax** [comment]
No, the server master branch (which is used in travis) moved to version 17 but the notes apps states that it's compatible with 14 to 16 https://github.com/nextcloud/notes/blob/84a4d7fb9947154ca97d4018ed0fb2a92d7f306b/appinfo/info.xml#L25

**Comment by tnyeanderson** [comment]
Should be good to go now :)

**Comment by tnyeanderson** [comment]
Whoops... Not sure what's wrong with my text editor (Atom), it is doing some weird indentation... It all looked right in Atom before I committed! NOW it should all be fixed :)

**Comment by korelstar** [comment]
Thank you very much for your contribution! I will review this as soon as possible (I'm currently on a journey).

**Comment by tnyeanderson** [comment]
Clicking doesn't work on mobile, and I had a bit of a lightbulb moment last night to make the functionality better.... so take time and enjoy your journeys! Give me a day or two and I will see if I can get mobile support and a couple other small improvements before its merged :)

**Comment by tnyeanderson** [comment]
Should be all set to go now! Maybe in the future we can add an option to hide completed events. Easily done with:

```
.CodeMirror-line.completed-task {
    display: none;
}
```

**Comment by tnyeanderson** [comment]
Oddly enough... it's like it signed itself....... Double check it and merge it in! :)

**Comment by korelstar** [comment]
No, I manually accepted this check, a few minutes ago. :D

I just tried your code, and I like it very much! Big thank you!

One question: are you done, now? I found only one issue: with Firefox on Android, toggling the checkbox works, but they are not shown as checkboxes - it looks like before your changes. Can you confirm this?

**Comment by tnyeanderson** [comment]
I am testing in a horrible way (just rsyncing the changed files to my own server to test), but I'm not seeing any issues. I saw similar issues with permissions because of the way I was testing, but once I got the permissions squared away and cleared my cache it loaded fine. Just downloaded Firefox on my LG V30 and not seeing any problems as of now. Sometimes the page would need a few reloads before notes.scss got reprocessed.

In the future, how should I be testing this? Clone the repo into the custom_apps folder and just switch between branches?

**Comment by korelstar** [comment]
I'm testing in an unprofessional way, too. The best way is to test at least with the latest version and with widespread versions of most important browsers. But since we are doing this in our free time, I think it's okay to do only those tests that are relatively effortless and fix bugs as soon as they are reported.

**Comment by GLLM** [comment]
Got it, you must use  hypen + space + [ ] ...

Sorry !

**Comment by korelstar** [comment]
@joelstitch Please open a new issue for that with more details, i.e. used browser, exact note's content, screenshot, etc.

**Pull request merged**
