### PR TITLE
Update table style

### PR DESCRIPTION
**Pull request by newhinton**
Signed-off-by: Felix Nüsse <felix.nuesse@t-online.de>

This uses a more modern table layout, inspired by the collectives app.

Also thanks to [Dai](https://stackoverflow.com/a/2586780) on Stackoverflow for the table-workaround!

### CODE REVIEW

**Comment by korelstar** [comment]
Could you please add some screenshots? (Before and after)

**Comment by newhinton** [comment]
| Original  | New |
| ------------- | ------------- |
| grafik | grafik |

The green tint is the hover-effect, similar to how text/collectives does it.

**Review by korelstar — CHANGES_REQUESTED** [review]
I really like your PR, the screenshot is looking good! However, I think your last commit was broken. Now, it looks like this:

Screenshot

Another thing: we should not use pixel units here. What about my suggested change?

**Comment by newhinton** [comment]
@korelstar sorry, what suggestion?

**Comment by korelstar** [comment]
> @korelstar sorry, what suggestion?

Sorry, my suggestion was lost (don't know why).

> Edit: My tests revealed that 0.75 em as padding works good.

This is too much from my perspective. I did a little adjustment and I think it's ready to merge, now.

**Pull request merged**
