### PR TITLE
More natural heading-1 size

### PR DESCRIPTION
**Pull request by andreasjacobsen93**
Decreased size of heading-1 to make it match the other headers more.
I felt it was way too big.

### CODE REVIEW

**Comment by korelstar** [comment]
IMHO something in the middle (32px?) would be fine.
/cc @jancborchardt

**Comment by jancborchardt** [comment]
Can you show a before-after comparison screenshot? :)

The h2 and h3 should match the 20px and 15px defined in https://github.com/nextcloud/server/blob/master/core/css/apps.scss, and the h1 here should look good with that. :)

**Comment by andreasjacobsen93** [comment]
headers

**Comment by jancborchardt** [comment]
Looks great! :+1: What do you think @nextcloud/notes?

**Comment by jancborchardt** [comment]
By the way @andreasjacobsen93 @korelstar it would be great to have you at the Nextcloud conference end of August in Berlin! https://nextcloud.com/conf/
Would be especially cool if you can give a lightning talk about your work on Nextcloud! :)

**Comment by Henni** [comment]
Looks better!

**Pull request merged**
