### PR TITLE
Update travis configuration

### PR DESCRIPTION
**Pull request by korelstar**
Dear Travis masters from @nextcloud/notes,

I've added some tests that I've found in another repository:
- [x] validate `appinfo/info.xml` against the XML schema
- [x] run `occ app:check-code`

### CODE REVIEW

**Comment by korelstar** [comment]
Just a note: due to the new validation of `appinfo/info.xml`, **Travis will fail** for this pull request, since `info.xml` is not valid, currently. However, this should be fixed in #34.

**Comment by Henni** [comment]
Ocular is used to `# Generate Code Coverage`
@korelstar would you mind changing this?

**Comment by korelstar** [comment]
@Henni done

**Comment by korelstar** [comment]
I've rebased this pull request and now it passes all checks. In favor of #36, I'm stopping my work on this. However, I propose to merge this nevertheless, since it enhances the current state and this may be helpful until Drone works fully.

**Pull request merged**
