### PR TITLE
Support for Windows (and other) line-breaks

### PR DESCRIPTION
**Pull request by korelstar**
Should fix owncloud/notes#246.
See also stefan-niedermann/OwnCloud-Notes#140.

### CODE REVIEW

**Comment by Henni** [comment]
@avalx does this fix your issue?

**Comment by Henni** [comment]
Looks good to me, but it would be great to get some feedback from some windows users which had this issue.

**Comment by korelstar** [comment]
See https://github.com/stefan-niedermann/OwnCloud-Notes/issues/140#issuecomment-267076044

**Comment by avalx** [comment]
Yes, I can confirm that this issue is resolved with the proposed changes.

**Comment by Henni** [comment]
@avalx Awesome! Let's get this in then!

**Pull request merged**
