### PR TITLE
Bump nextcloud-axios from 0.1.3 to 0.2.0

### PR DESCRIPTION
**Pull request by ChristophWurst**
I would generally suggest adding Dependabot to this repo.

### CODE REVIEW

**Comment by korelstar** [comment]
@ChristophWurst Thanks for this update. Is it possible to enable Dependabot for security updates only? I don't like that Dependabot spams the git log and PR list by default. I would like to manually use `npm-upgrade` but a notification for security updates would be nice.

**Comment by ChristophWurst** [comment]
yes

Bildschirmfoto von 2019-05-31 11-33-44

**Comment by korelstar** [comment]
Nice! Let's do this :-)

Do you have the permissions to activate this?

**Comment by ChristophWurst** [comment]
Nope :man_shrugging: maybe @skjnldsv can help

**Comment by korelstar** [comment]
Maybe someone could also add me to the security alerts: https://help.github.com/en/articles/managing-alerts-for-vulnerable-dependencies-in-your-organizations-repositories

/cc @MorrisJobke or @rullzer ?

Thanks!

**Comment by korelstar** [comment]
Are there any news on configuring security alerts for this repository? @MorrisJobke @rullzer @jancborchardt

**Comment by skjnldsv** [comment]
All done. Security updates enabled.
Also, you're now admin of this repo, no idea why you were not before! :scream_cat: 
https://github.com/nextcloud/notes/network/alerts

For debendabot, I would actually prefer to have it for all packages as it's easier to be always up-to-date than skipping 3 major at once because we did not updated in 1 year :cry: 
What is exactly bothering you with dependabot? We usually enable it on sunday morning only for minimal nuisance :smile: 
I can even set it as one per month :wink: 

Also, I enabled and selected the option after where I should have selected the option and enable..., so it might create pull request initially. Sorry about that! :see_no_evil:

**Comment by skjnldsv** [comment]
> My doubt about dependabot is that it pollutes the commit history. But if you would set it to be executed once per month, I'm fine with it.

Well, sure, you'll get dependencies merges. ^^
Let's go for one per month then :+1:

**Pull request merged**
