### PR TITLE
Improved error handling

### LINKED ISSUE #568: NextCloud Notes being locked constantly
**Describe the bug**
When editing notes on browser, i get a message telling "Note is being locked", having to wait for some seconds till the system recognizes the note again:

**To Reproduce**
Just create a new note, the message appears rear some seconds of writting.

**Expected behavior**
Work without this message interruptions

**Screenshots**
image

Directory isn't accessible (note path) is locked, please choose a valid route on Configuration.

**Server (please complete the following information):**
- Notes app version: 3.6.0
- Nextcloud version: 19.0.0
- OS: linuxserver.io docker container (Linux 4.19.118-v7l+ armv7l) --> alpine 3.12
- Web server: nginx version: nginx/1.18.0
- PHP version: 7.3.18
- Database: mysql 10.1.44

**Client (please complete the following information):**
 - Browser (incl. version): Firefox 78.0.2, happens also on Chrome 83 and Chromium, previous versions also.
 - OS: Linux (tested on Fedora 32 and Arch Linux) and Windows 10.

### PR DESCRIPTION
**Pull request by korelstar**
The following adjustments where done in order to fix #568 :

- [x] improve error handling (better error messages, don't block app when refreshing notes list fails)
- [x] update meta after content update
- [x] retry if locked

### CODE REVIEW

**Comment by mikelupe** [comment]
Hello,
when will this fix be rolled out? I've got the very same problem for the last 2 months like https://github.com/nextcloud/notes/issues/568  . Impossible to work with Web notes.

Thank you
regards

**Comment by korelstar** [comment]
The release is ready, but there was a problem with the app store last week. This week, I'm on vacation. So I can't make it before Sunday, sorry.

In the meanwhile, you can download the release from the GitHub release page.

**Comment by mikelupe** [comment]
Hey, thanks. Enjoy your vacations!

> The release is ready, but there was a problem with the app store last week. This week, I'm on vacation. So I can't make it before Sunday, sorry.
>

**Comment by mikelupe** [comment]
@korelstar Don't rush, next week will be ok. I installed latest from git but unfortunately this doesn't solve it - when creating new notes it still mourns about being locked.

**Comment by korelstar** [comment]
Please use this download for testing:
https://github.com/nextcloud/notes/releases/download/v3.6.1/notes.tar.gz

If the error persists, please open a new issue with detailed information using the issue template.

**Comment by mikelupe** [comment]
@korelstar Thanks for replying. I tried that version, it still breaks with errors on NewNote(1), NewNote(2) etc. as already described in https://github.com/nextcloud/notes/issues/568. I unfortunately don't find the time to create a new issue.

**Comment by mikelupe** [comment]
@korelstar Will there be an update for notes, as mentioned it's still a problem. Thanks.

**Comment by korelstar** [comment]
@mikelupe please see https://github.com/nextcloud/notes/pull/573#issuecomment-662409292

**Comment by mikelupe** [comment]
@korelstar Thank you, since the official update to 3.6.2 it seems to work really fine. Do you know what could have been the reason?

**Pull request merged**
