### PR TITLE
Drone CI

### PR DESCRIPTION
**Pull request by Henni**

### CODE REVIEW

**Comment by korelstar** [comment]
Do you plan to replace Travis by Drone? Or should Drone be used in addition to Travis? (Would this make sense?)
This would be interesting for #35 in order to avoid to do obsolete work.

**Comment by Henni** [comment]
@korelstar yeah. It would be great if we could use Drone CI instead of Travis. (Nextcloud power :muscle:)
But I'd like to integrate your changes (like info.xml validation)

Additionally I currently have no idea why drone fails on this specific error. I believe this is an error that actually exists but wasn't caught by travis for some obscure reason.
@korelstar maybe you have an idea!?

**Comment by korelstar** [comment]
On the first view, I do not understand this neither, but I'm not familiar with Drone and phpunit.

**Comment by Henni** [comment]
rebased to current master (v.2.2.0)

**Comment by jancborchardt** [comment]
@korelstar @Henni any update on this one (and https://github.com/nextcloud/notes/pull/52)? @camilasan @MorrisJobke can you help?

**Comment by korelstar** [comment]
No, I still have no experiences with Drone. Some help would be great :-)

**Comment by MorrisJobke** [comment]
> No, I still have no experiences with Drone. Some help would be great :-)

Okay - I can help. Could you rebase and also I would say, that we should do this step by step and not all in one to keep the overview.

**Comment by jancborchardt** [comment]
@MorrisJobke this seems rebased? (Has no conflicts with master)

**Comment by MorrisJobke** [comment]
Could you rebase again and then ping me? So I get a notification. Sorry for missing it last time.

**Comment by jancborchardt** [comment]
@Henni @korelstar @camilasan does someone of you more technically inclined folks mind rebasing this? :)

**Comment by korelstar** [comment]
@jancborchardt 
This PR was created by @Henni and I have absolutely no knowledge of Drone. Therefore, I have not an exactly idea of how to solve the current conflict (`tests/integration/controller/NotesApiControllerTest.php`).

Would be nice if @Henni could continue on this.

**Comment by korelstar** [comment]
Closing, since we have no progress for a very long time and the code is outdated in the meanwhile.

**Pull request closed without merging**
