### PR TITLE
Default note view

### PR DESCRIPTION
**Pull request by zaphodus**
Set preview mode for notes that already exist.
#352

### CODE REVIEW

**Comment by korelstar** [comment]
Thanks for your contribution!

Opening a note in edit mode is intended behavior since this app is primarily for editing notes and not just for viewing notes. However, I think you won't need this change anymore, after #331 is realized.

**Comment by zaphodus** [comment]
Okay, that might be interesting.

**Comment by manfredu** [comment]
> 
> Opening a note in edit mode is intended behavior since this app is primarily for editing notes and not just for viewing notes. However, I think you won't need this change anymore, after #331 is realized.

Then what is the proposed way to view notes? I use my notes as a searchable knowledge base and therefore I would very much like to have an option to see existing notes formatted and not in edit mode.

I do agree that the integration of Nextcloud Text would solve this issue (and others as well) . Has work on this already started?  When is this expected to be available?

Thanks!

**Comment by manfredu** [comment]
Maybe this contribution could be merged as a temporary solution in case the realization of #331 will still take a while...?

**Comment by korelstar** [comment]
No, sorry. We hadn't enough free time for this, yet.

I would accept a PR for a default view mode setting as interim solution, though.

**Pull request closed without merging**
