### PR TITLE
new Settings API

### PR DESCRIPTION
**Pull request by korelstar**
Provides access to the app settings through the API. This was requested in https://github.com/stefan-niedermann/nextcloud-notes/issues/916#issuecomment-711148998. However, my implementation differs to the proposed API. Please check, if this is fine for you, too @stefan-niedermann . My approach was easier :grin: 
Please note, that the API does not provide the list of allowed file suffixes. This is static for now. We could add a dynamic list later. Is this fine?

- [x] new API endpoints for getting and setting app settings
- [x] documentation for API changes
- [x] Test cases

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
Now that looks awesome, i like the approach 🙂 

I am missing two things here in the documentation:
- Error codes, for example:
  - providing a invalid value as file extension
  - use `../` or `/` or `1337` as value for the folder
- Some kind of "reset" - A client does not know the localized term of "Notes" in the server app and has to guess therefore if the user wants to reset the settings to default

**Comment by korelstar** [comment]
Thanks for the feedback!

Currently, the request succeeds even if the values are invalid. The server performs a sanitation of the values and sends back the fixed values.
- `fileSuffix`: if the value is not allowed, the default value is used.
- `notesPath`: the path is sanitized, i.e. unnecessary `./`, `X/../`, `//` are removed.

I've added the following sentences to the documentation:
> Empty values are replaced by the settings attribute's default value. All values are sanitized (e.g. prevent path traversal attacks, check allowed suffixes), so the result can differ from the request (the request will still succeed). The client may show an information to the user if the response differs from the request.

Is this sufficient?

**Comment by stefan-niedermann** [comment]
Yes :)

So in my understanding, if i push the object:

```json
{
  "fileSuffix": null,
  "notesPath": null
}
```

the sanitizer will map it to roughly this values (and return it in the response):

```json
{
  "fileSuffix": ".txt",
  "notesPath": "Notes"
}
```

**Comment by korelstar** [comment]
Yep, that's correct

**Comment by stefan-niedermann** [comment]
I have kind of a [working implementation](https://github.com/stefan-niedermann/nextcloud-notes/pull/1091/files), i think. Looking forward to test this with a real server :)

**Comment by korelstar** [comment]
> I have kind of a [working implementation](https://github.com/stefan-niedermann/nextcloud-notes/pull/1091/files), i think. Looking forward to test this with a real server :)

What do you mean with "real server"? You can checkout this branch and install it. Did you do such tests in the meanwhile?

**Comment by stefan-niedermann** [comment]
Nah, nevermind :smile: I just don't have a test instance right now where i could push the state from the branch. When i have time i will set up one.

**Pull request merged**
